platform :ios, '6.0'

pod 'Reachability'
pod 'CustomBadge'
pod 'EGOTableViewPullRefresh'
pod 'ISO8601DateFormatter'
pod 'JSONKit'
pod 'AJNotificationView'
pod 'NSData+Base64'
pod 'OpenSSL', :git => 'https://github.com/yaakov-h/OpenSSL'
